# Generated by Django 2.0 on 2020-03-13 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='studio_review',
        ),
    ]
