# Generated by Django 2.0 on 2020-03-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200313_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='school_review',
            field=models.TextField(max_length=550),
        ),
    ]
