# Generated by Django 2.0 on 2020-02-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200224_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='files',
            field=models.ImageField(blank=True, upload_to='blogs/%Y/%m/%d'),
        ),
    ]
