# Generated by Django 2.0 on 2020-02-26 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='files',
        ),
    ]
