# Generated by Django 2.0 on 2020-02-27 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_likes',
        ),
    ]
