# Generated by Django 2.0 on 2020-02-27 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_postlike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postlike',
            old_name='post',
            new_name='post_name',
        ),
    ]
