# Generated by Django 2.0 on 2020-03-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200227_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, default='blog.jpg', upload_to='blogs/%Y/%m/%d'),
        ),
    ]
