# Generated by Django 2.0 on 2020-03-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200324_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, default='blog1.jpg', upload_to='blogs/%Y/%m/%d'),
        ),
    ]
