# Generated by Django 2.0 on 2020-03-16 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200316_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='date_start',
        ),
    ]
