# Generated by Django 2.0 on 2020-03-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_reviewstudio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewstudio',
            name='studio_review',
            field=models.TextField(max_length=500),
        ),
    ]
