# Generated by Django 2.0 on 2020-03-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_masters'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masters',
            options={'ordering': ('-created',), 'verbose_name': 'Мастера', 'verbose_name_plural': 'Мастера'},
        ),
        migrations.AddField(
            model_name='masters',
            name='direction',
            field=models.CharField(default='position', max_length=150),
        ),
        migrations.AddField(
            model_name='masters',
            name='position',
            field=models.CharField(default='position', max_length=50),
        ),
    ]
