# Generated by Django 2.0 on 2020-03-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200319_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='shop.png', upload_to='products/%Y/%m/%d'),
        ),
    ]
