# Generated by Django 2.0 on 2020-03-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200324_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masters',
            name='photo',
            field=models.ImageField(blank=True, default='teacher.jpg', upload_to='master/%Y/%m/%d'),
        ),
    ]
