# Generated by Django 2.0 on 2020-03-13 07:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.PositiveIntegerField(validators=[django.core.validators.RegexValidator('^\\d+$', 'Only numeric characters are allowed.'), django.core.validators.MaxLengthValidator]),
        ),
    ]
